name: BattlePass
version: 1.4
main: battlepass.main.Battlepass
author: Amber
description: Players love to hate on this.
api-version: 1.16
depend:
  - Vault

commands:
  battlepass:
    description: Main battlepass command
    usage: /<command> <reload|setxp|addxp|checkxp|top|open>
    aliases: [bpass]

permissions:
  battlepass.use:
    description: Allows the player to use the battlepass
    default: true

  battlepass.top:
    description: Allows the player to check the top battlepass players
    default: true

  battlepass.reload:
    description: Allows the player to reload the battlepass configuration
    default: op

  battlepass.premium:
    description: Allows the player to use premium battlepass
    default: false

  battlepass.setxp:
    description: Allows to set battlepass xp of a player
    default: op

  battlepass.addxp:
    description: Allows to add battlepass xp to a player
    default: op
  
  battlepass.checkxp:
    description: Allows to check battlepass xp of a player
    default: op

  battlepass.multiplier:
    description: Allows to set the battlepass multiplier
    default: false